stages:
  data_ingestion:
    cmd: py -m src.stockPrediction.pipeline.stage_01_data_ingestion_pipeline
    deps:
      - src/stockPrediction/pipeline/stage_01_data_ingestion_pipeline.py
      - src/stockPrediction/components/data_ingestion.py
    params:
      - config/config.yaml:
        - data_ingestion
  data_validation:
    cmd: py -m src.stockPrediction.pipeline.stage_02_data_validation_pipeline
    deps:
      - src/stockPrediction/pipeline/stage_02_data_validation_pipeline.py
      - src/stockPrediction/components/data_validation.py
      - src/stockPrediction/pipeline/stage_01_data_ingestion_pipeline.py
      - src/stockPrediction/components/data_ingestion.py
    params:
      - config/config.yaml:
        - data_validation
      - schema.yaml:
    outs:
      - artifacts/data_validation/status.txt
  data_transformation:
    cmd: py -m src.stockPrediction.pipeline.stage_03_data_transformation_pipeline
    deps:
      - src/stockPrediction/pipeline/stage_03_data_transformation_pipeline.py
      - src/stockPrediction/components/data_transformation.py
    params:
      - config/config.yaml:
        - data_transformation
    outs:
      - artifacts/data_transformation/processed_dataset.csv
      - artifacts/data_transformation/train.csv
      - artifacts/data_transformation/test.csv
      - artifacts/data_transformation/preprocessor.pkl
  data_training:
    cmd: py -m src.stockPrediction.pipeline.stage_04_data_training_pipeline
    deps: 
      - src/stockPrediction/pipeline/stage_04_data_training_pipeline.py
      - src/stockPrediction/components/data_trainer.py
    params:
      - config/config.yaml:
        - model_trainer
    