artifacts_root: artifacts/raw_data/

data_ingestion:
  symbol: SBIN 
  local_data_file_path: artifacts/raw_data/dataset.csv
  start_year: 2019

data_validation:
  root_dir: artifacts/data_validation
  dataset_file_path: artifacts/raw_data/CAR_DETAILS_FROM_CAR_DEKHO.csv
  validation_status_file_path: artifacts/data_validation/status.txt

data_transformation:
  root_dir: artifacts/data_transformation
  dataset_file_path: artifacts/raw_data/CAR_DETAILS_FROM_CAR_DEKHO.csv
  processed_dataset_file_path: artifacts/data_transformation/processed_dataset.csv
  preprocessor_obj_path: artifacts/data_transformation/proprocessor.pkl
  dataset_summary_path: artifacts/data_transformation/dataset_summary.txt
  test_size: 0.3
  random_state: 10
  train_dataset_file_path: artifacts/data_transformation/train.csv
  test_dataset_file_path: artifacts/data_transformation/test.csv

model_trainer:
  root_dir: artifacts/model_trainer
  train_data_path: artifacts/data_transformation/train.csv
  test_data_path: artifacts/data_transformation/test.csv
  model_name: model.pkl

model_evaluation:
  root_dir: artifacts/model_evaluation
  mlflow_uri: https://dagshub.com/jayarajmadanu/car-price-prediction.mlflow
  test_data_path: artifacts/data_transformation/test.csv
  model_path: artifacts/model_trainer/model.pkl

prediction_config:
  model_path: artifacts/model_trainer/model.pkl
  preprocessor_path: artifacts/data_transformation/proprocessor.pkl

